iprlib: Export missing prototypes in header file
ipr_device_lock(), ipr_device_unlock() and get_scsi_dev_data() all get
used outside of iprlib.c but they were missing a prototype in the
library header file.  This patch adds it to silently the following
warnings:

../iprconfig.c: In function ‘wait_for_formatted_af_dasd’:
../iprconfig.c:240:14: warning: implicit declaration of function ‘get_scsi_dev_data’ [-Wimplicit-function-declaration]
   num_devs = get_scsi_dev_data(&scsi_devs);
              ^~~~~~~~~~~~~~~~~
../iprconfig.c: In function ‘verify_device’:
../iprconfig.c:1711:6: warning: implicit declaration of function ‘ipr_device_lock’ [-Wimplicit-function-declaration]
  if (ipr_device_lock(dev))
      ^~~~~~~~~~~~~~~
../iprconfig.c:1741:2: warning: implicit declaration of function ‘ipr_device_unlock’ [-Wimplicit-function-declaration]
  ipr_device_unlock(dev);
  ^~~~~~~~~~~~~~~~~

Signed-off-by: Gabriel Krisman Bertazi <krisman@linux.vnet.ibm.com>
Signed-off-by: Brian King <brking@linux.vnet.ibm.com>